version: "3.9"

services:
  auto:
    build: ./services/AUTOMATIC1111
    ports:
      - 7860:7860
    volumes:
      - ./data:/data
      - ./output:/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities:
                - "compute"
                - "utility"

    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
